### ISSUE TITLE
Questions about Keybinds

### ISSUE THREAD

**Issue by ESMKarameru** [bozzobrain/LethalCompanyInstantLoot#1]
I have a question regarding the keybinds of the mod.

I understand that you can change the keybind to a latter, for example "L" is the default, and I just change it to "P".

However, what if I want to change the keybind to numbers, like "0", or a sign, like "-" or "=" or "+" then what should I do in the config file?

**Comment by bozzobrain** [comment]
I determined that you can use the Alpha keybinds 0-9 for numbers that are at the top of the regular keyboard by using the associate number in the same format
<Keyboard>/0
<Keyboard>/0
<Keyboard>/0
<Keyboard>/0
<Keyboard>/0

**Comment by bozzobrain** [comment]
I determined that you can use the Alpha keybinds 0-9 for numbers that are at the top of the regular keyboard by using the associate number in the same format:
\<Keyboard>/0
\<Keyboard>/1
\<Keyboard>/2
.
.
.

As for the '+','-','='. Looking into that now.

**Comment by bozzobrain** [comment]
Turns out that you can use any of the keybinds that are in [Unity's InputSystem Documentation](https://github.com/Unity-Technologies/InputSystem/blob/develop/Packages/com.unity.inputsystem/InputSystem/Devices/Keyboard.cs). While this may have been something that should be obvious it took me entirely too long to find this reference. BepInEx documentation could really benefit from having this better documented and easier to find.

Examples:
\<Keyboard>/minus = '-'
\<Keyboard>/equals = '='
\<Keyboard>/numpadMinus = '-' (Numpad only)
\<Keyboard>/pageup
\<Keyboard>/pagedown
\<Keyboard>/numpad0
\<Keyboard>/numpadMultiply
\<Keyboard>/numpadMinus

These appear to be case insensitive.

**Comment by ESMKarameru** [comment]
Thank you so much!
